import { AgentForgeConfig, SyncOutput } from './types';

export function generateAiderRules(config: AgentForgeConfig): SyncOutput {
  const files: SyncOutput['files'] = [];

  // 1. .aider.conf.yml
  const confLines: string[] = [
    `# Aider Configuration - Generated by AgentForge`,
    `auto-commits: false`,
    `dark-mode: true`,
    `read: .aider.prompt.md`,
    `test-cmd: "${config.stack?.testRunner || 'npm test'}"`,
    `auto-test: true`
  ];

  files.push({
    path: '.aider.conf.yml',
    content: confLines.join('\n'),
    action: 'created'
  });

  // 2. .aider.prompt.md
  const promptLines: string[] = [
    `# Aider System Prompt Directives`,
    `Project: ${config.name}`,
    ``,
    `## Core Directives`,
    ...config.rules.core.map(r => `- ${r}`),
    ``,
    `## Stack`,
    `- Languages: ${(config.stack?.languages || ['TypeScript']).join(', ')}`,
    `- Test Runner: ${config.stack?.testRunner || 'npm test'}`
  ];

  files.push({
    path: '.aider.prompt.md',
    content: promptLines.join('\n'),
    action: 'created'
  });

  return {
    agent: 'aider',
    files
  };
}
