import { AgentForgeConfig, SyncOutput } from './types';

export function generateAntigravityRules(config: AgentForgeConfig): SyncOutput {
  const files: SyncOutput['files'] = [];

  // 1. .agents/AGENTS.md
  const lines: string[] = [
    `# Google Antigravity Agent Directives - Generated by AgentForge`,
    `# Project: ${config.name} (${config.description || 'Modern AI Workspace'})`,
    ``,
    `## Engineering Directives`,
    ...config.rules.core.map(r => `- ${r}`),
    ``,
    `## Tech Stack & Tooling`,
    `- Languages: ${(config.stack?.languages || ['TypeScript']).join(', ')}`,
    `- Frameworks: ${(config.stack?.frameworks || ['Node.js']).join(', ')}`,
    `- Test Command: ${config.stack?.testRunner || 'npm test'}`,
    ``
  ];

  if (config.rules.architecture?.length) {
    lines.push(`## Architecture & Modularity`, ...config.rules.architecture.map(r => `- ${r}`), ``);
  }
  if (config.rules.security?.length) {
    lines.push(`## Security Standards`, ...config.rules.security.map(r => `- ${r}`), ``);
  }
  if (config.rules.testing?.length) {
    lines.push(`## Testing Protocols`, ...config.rules.testing.map(r => `- ${r}`), ``);
  }

  files.push({
    path: '.agents/AGENTS.md',
    content: lines.join('\n'),
    action: 'created'
  });

  return {
    agent: 'antigravity',
    files
  };
}
