import { AgentForgeConfig, SyncOutput } from './types';

export function generateClaudeRules(config: AgentForgeConfig): SyncOutput {
  const lines: string[] = [
    `# CLAUDE.md - Project Directives for Claude Code`,
    `# Generated by AgentForge (https://github.com/mrzroot/agentforge)`,
    ``,
    `## Project Overview: ${config.name}`,
    `${config.description || 'AI-assisted modern codebase.'}`,
    ``,
    `## Commands & Environment`,
    `- Build / Compile: \`npm run build\` (or equivalent)`,
    `- Run Tests: \`${config.stack?.testRunner || 'npm test'}\``,
    `- Package Manager: \`${config.stack?.packageManager || 'npm'}\``,
    `- Runtime / Languages: ${(config.stack?.languages || ['TypeScript']).join(', ')}`,
    ``,
    `## Code Architecture & Philosophy`,
    ...config.rules.core.map(r => `- ${r}`),
    ``
  ];

  if (config.rules.architecture?.length) {
    lines.push(`## Architectural Conventions`, ...config.rules.architecture.map(r => `- ${r}`), ``);
  }
  if (config.rules.security?.length) {
    lines.push(`## Security Standards`, ...config.rules.security.map(r => `- ${r}`), ``);
  }
  if (config.rules.testing?.length) {
    lines.push(`## Testing Requirements`, ...config.rules.testing.map(r => `- ${r}`), ``);
  }
  if (config.rules.git?.length) {
    lines.push(`## Git Commit Standards`, ...config.rules.git.map(r => `- ${r}`), ``);
  }

  return {
    agent: 'claude',
    files: [
      {
        path: 'CLAUDE.md',
        content: lines.join('\n'),
        action: 'created'
      }
    ]
  };
}
