import { AgentForgeConfig, SyncOutput } from './types';

export function generateClineRules(config: AgentForgeConfig): SyncOutput {
  const lines: string[] = [
    `# Cline & Roo Code Custom Instructions - Generated by AgentForge`,
    `# Project: ${config.name}`,
    ``,
    `## General Instructions`,
    ...config.rules.core.map(r => `- ${r}`),
    ``,
    `## Environment`,
    `- Languages: ${(config.stack?.languages || ['TypeScript']).join(', ')}`,
    `- Frameworks: ${(config.stack?.frameworks || ['Node.js']).join(', ')}`,
    `- Test Command: ${config.stack?.testRunner || 'npm test'}`,
    ``
  ];

  if (config.rules.architecture?.length) {
    lines.push(`## Architecture`, ...config.rules.architecture.map(r => `- ${r}`), ``);
  }
  if (config.rules.security?.length) {
    lines.push(`## Security`, ...config.rules.security.map(r => `- ${r}`), ``);
  }

  return {
    agent: 'cline',
    files: [
      {
        path: '.clinerules',
        content: lines.join('\n'),
        action: 'created'
      }
    ]
  };
}
