import { AgentForgeConfig, SyncOutput } from './types';

export function generateCopilotRules(config: AgentForgeConfig): SyncOutput {
  const lines: string[] = [
    `# GitHub Copilot Custom Instructions`,
    `# Generated by AgentForge (https://github.com/mrzroot/agentforge)`,
    ``,
    `## Project: ${config.name}`,
    `${config.description || 'AI-assisted modern codebase.'}`,
    ``,
    `## Coding Guidelines`,
    ...config.rules.core.map(r => `- ${r}`),
    ``,
    `## Security & Architecture`,
    ...(config.rules.security || []).map(r => `- ${r}`),
    ...(config.rules.architecture || []).map(r => `- ${r}`),
    ``,
    `## Testing Instructions`,
    ...(config.rules.testing || []).map(r => `- ${r}`),
    ``
  ];

  return {
    agent: 'copilot',
    files: [
      {
        path: '.github/copilot-instructions.md',
        content: lines.join('\n'),
        action: 'created'
      }
    ]
  };
}
