import { AgentForgeConfig, SyncOutput } from './types';

export function generateCursorRules(config: AgentForgeConfig): SyncOutput {
  const files: SyncOutput['files'] = [];

  // 1. Root .cursorrules (Legacy & Universal fallback)
  const rootLines: string[] = [
    `# Cursor AI Project Rules - Generated by AgentForge`,
    `# Project: ${config.name} (${config.description || 'AI-Assisted'})`,
    ``,
    `## Tech Stack`,
    `- Languages: ${(config.stack?.languages || ['TypeScript']).join(', ')}`,
    `- Frameworks: ${(config.stack?.frameworks || ['Node.js']).join(', ')}`,
    `- Package Manager: ${config.stack?.packageManager || 'npm'}`,
    `- Test Command: ${config.stack?.testRunner || 'npm test'}`,
    ``,
    `## Core Directives`,
    ...config.rules.core.map(r => `- ${r}`),
    ``
  ];

  if (config.rules.architecture?.length) {
    rootLines.push(`## Architectural Standards`, ...config.rules.architecture.map(r => `- ${r}`), ``);
  }
  if (config.rules.security?.length) {
    rootLines.push(`## Security & Input Validation`, ...config.rules.security.map(r => `- ${r}`), ``);
  }
  if (config.rules.testing?.length) {
    rootLines.push(`## Testing & Quality`, ...config.rules.testing.map(r => `- ${r}`), ``);
  }
  if (config.rules.git?.length) {
    rootLines.push(`## Git & Commits`, ...config.rules.git.map(r => `- ${r}`), ``);
  }
  if (config.rules.custom?.length) {
    config.rules.custom.forEach(g => {
      rootLines.push(`## ${g.name}`, ...(g.description ? [`*${g.description}*`] : []), ...g.rules.map(r => `- ${r}`), ``);
    });
  }

  files.push({
    path: '.cursorrules',
    content: rootLines.join('\n'),
    action: 'created'
  });

  // 2. Modern Cursor Rules (.cursor/rules/project-rules.mdc)
  const mdcContent = [
    `---`,
    `description: Global project rules and architecture standards for ${config.name}`,
    `globs: *`,
    `alwaysApply: true`,
    `---`,
    ``,
    `# ${config.name} Development Guidelines`,
    ``,
    `## 1. Core Principles`,
    ...config.rules.core.map(r => `- ${r}`),
    ``,
    `## 2. Architecture & Patterns`,
    ...(config.rules.architecture || ['Maintain clean separation of concerns.']).map(r => `- ${r}`),
    ``,
    `## 3. Security Requirements`,
    ...(config.rules.security || ['Never hardcode credentials or secrets.']).map(r => `- ${r}`),
    ``,
    `## 4. Testing Protocols`,
    ...(config.rules.testing || ['Ensure automated tests pass before finalizing edits.']).map(r => `- ${r}`),
    ``
  ].join('\n');

  files.push({
    path: '.cursor/rules/project-rules.mdc',
    content: mdcContent,
    action: 'created'
  });

  return {
    agent: 'cursor',
    files
  };
}
