import { AgentForgeConfig, SyncOutput } from './types';

export function generateWindsurfRules(config: AgentForgeConfig): SyncOutput {
  const lines: string[] = [
    `# Windsurf & Cascade Directives - Generated by AgentForge`,
    `# Project: ${config.name}`,
    ``,
    `## Global Instructions`,
    ...config.rules.core.map(r => `- ${r}`),
    ``,
    `## Stack Details`,
    `- Languages: ${(config.stack?.languages || ['TypeScript']).join(', ')}`,
    `- Frameworks: ${(config.stack?.frameworks || ['Node.js']).join(', ')}`,
    `- Test Runner: ${config.stack?.testRunner || 'npm test'}`,
    ``
  ];

  if (config.rules.architecture?.length) {
    lines.push(`## Architecture Rules`, ...config.rules.architecture.map(r => `- ${r}`), ``);
  }
  if (config.rules.security?.length) {
    lines.push(`## Security & Input Sanitization`, ...config.rules.security.map(r => `- ${r}`), ``);
  }
  if (config.rules.testing?.length) {
    lines.push(`## Quality & Testing`, ...config.rules.testing.map(r => `- ${r}`), ``);
  }

  return {
    agent: 'windsurf',
    files: [
      {
        path: '.windsurfrules',
        content: lines.join('\n'),
        action: 'created'
      }
    ]
  };
}
