import fs from 'fs';
import path from 'path';
import { globSync } from 'glob';
import { extractSkeleton, CompressedCode } from './ast-extractor';
import { calculateTokenSavings, TokenStats } from '../../utils/tokens';
import { AgentForgeConfig } from '../sync/types';

export interface PackedRepo {
  markdown: string;
  files: {
    path: string;
    stats: TokenStats;
    language: string;
  }[];
  totalStats: TokenStats;
}

export function packRepository(
  config: AgentForgeConfig,
  options: { cwd?: string; skeletonizeAll?: boolean; targetGlobs?: string[] } = {}
): PackedRepo {
  const cwd = options.cwd || process.cwd();
  const includeGlobs = options.targetGlobs?.length ? options.targetGlobs : (config.compression?.include || ['src/**/*', 'lib/**/*']);
  const excludeGlobs = config.compression?.exclude || ['node_modules/**', 'dist/**', 'build/**', '.git/**', '*.lock', '*.min.js'];

  const matchedFiles: string[] = [];
  for (const pattern of includeGlobs) {
    const files = globSync(pattern, {
      cwd,
      nodir: true,
      ignore: excludeGlobs,
      dot: false
    });
    matchedFiles.push(...files);
  }

  const uniqueFiles = Array.from(new Set(matchedFiles)).sort();
  const packedFiles: PackedRepo['files'] = [];
  const mdParts: string[] = [];

  mdParts.push(`# Project Context Bundle: ${config.name}`);
  mdParts.push(`Generated by AgentForge (Token-Killer AST Compressor)\n`);
  mdParts.push(`## Repository File Tree & Index`);

  for (const relPath of uniqueFiles) {
    mdParts.push(`- \`${relPath}\``);
  }
  mdParts.push(`\n---\n`);

  let aggregatedOriginal = '';
  let aggregatedCompressed = '';

  for (const relPath of uniqueFiles) {
    const fullPath = path.join(cwd, relPath);
    if (!fs.existsSync(fullPath)) continue;

    const rawContent = fs.readFileSync(fullPath, 'utf-8');
    const skeleton = extractSkeleton(rawContent, relPath);
    const contentToUse = options.skeletonizeAll !== false ? skeleton.skeletonCode : rawContent;

    const stats = calculateTokenSavings(rawContent, contentToUse);
    packedFiles.push({
      path: relPath,
      stats,
      language: skeleton.language
    });

    aggregatedOriginal += rawContent + '\n';
    aggregatedCompressed += contentToUse + '\n';

    mdParts.push(`### File: \`${relPath}\` (${skeleton.language})`);
    mdParts.push(`*Tokens: ~${stats.compressedTokens} (Original: ~${stats.originalTokens}, Saved: ${stats.savingsPercentage}%)*`);
    mdParts.push(`\`\`\`${skeleton.language}\n${contentToUse}\n\`\`\`\n`);
  }

  const totalStats = calculateTokenSavings(aggregatedOriginal, aggregatedCompressed);

  return {
    markdown: mdParts.join('\n'),
    files: packedFiles,
    totalStats
  };
}
